export const GET_VIDEOGAMES = 'getVideogames'
export const GET_DETAIL = 'getVideogameDetail'
export const CLEAN_DETAIL = 'getVideogameDetail'
export const GET_GENRES = 'getGenres'
export const SEARCH_VIDEOGAMES = 'searchVideogames'
// export const UPDATE_FILTER = 'updateFilters'
export const CREATE_VIDEOGAME = 'createVideogame'
export const IS_LOADING = 'isLoading'